# Persistent Volume must be created before a pod can claim it

apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflowdags-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: /tmp/airflow-pv/
